<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.julian_n</groupId>
        <artifactId>abarrotesprogra2_00000279037</artifactId>
        <version>1.0.2</version>
    </parent>
    <artifactId>objetosfachada</artifactId>
    <packaging>jar</packaging>
    <properties>
        <exec.mainClass>objetosfachada.Objetosfachada</exec.mainClass>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.julian_n</groupId>
            <artifactId>objetosdominio</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.julian_n</groupId>
            <artifactId>objetosservicio</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.julian_n</groupId>
            <artifactId>objetospersistencia</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.julian_n</groupId>
            <artifactId>objetoslogicapersistencia</artifactId>
            <version>1.0.2</version>
        </dependency>
    </dependencies>
</project>